image: mcr.microsoft.com/playwright:v1.52.0-noble

pipelines:
  default:
    - step:
        name: Run tests on main branch Push
        caches:
          - node
        script:
          - npm ci
          - npx playwright install --with-deps
          - npm run test
        artifacts:
          - playwright-report/**
  pull-requests:
    '**':
      - step:
          name: Run tests on Pull Request to main
          condition:
            changesets:
              includePaths:
                - '**'
          caches:
            - node
          script:
            - npm ci
            - npx playwright install --with-deps
            - npm run test
          artifacts:
            - playwright-report/**
